#!/bin/bash
pulseaudio --start &
sxhkd &
pa-applet &
nm-applet &
compton &
numlockx &
octoxbps-notifier &
xscreensaver -nosplash &
xfce4-panel &
nemo-desktop &
ulauncher &
/usr/libexec/notification-daemon &
xautolock -detectsleep -time 5 -locker "betterlockscreen -l blur -w /path/to/your/wallpaper.png" -killtime 10 -killer "zzz -z"
blueman-applet &!
