#!/bin/bash
pulseaudio --start &
sxhkd &
pa-applet &
nm-applet &
compton &
numlockx &
xscreensaver -nosplash &
xfce4-panel &
nemo-desktop &
ulauncher &
/usr/libexec/notification-daemon &
xautolock -detectsleep -time 5 -locker "betterlockscreen -l blur -w ~/.config/betterlockscreen/pexels-eberhard-grossgasteiger-640781.jpg" -killtime 10 -killer "sudo zzz -z"
blueman-applet &!
